const fs = require("fs");
const code = fs.readFileSync("docs/engine.worker.js", "utf8");
const messages = [];
global.self = { postMessage: (m) => messages.push(m) };
(0, eval)(code);
const f = (t) => [Math.cos(t)/(1+Math.sin(t)**2), Math.sin(t)*Math.cos(t)/(1+Math.sin(t)**2)];
const pts = Array.from({length: 220}, (_, i) => { const [x,y] = f(i/220*2*Math.PI); return [x*2, y*2]; });
global.self.onmessage({ data: { points: pts, cfg: { generations: 320, popsize: 200, seed: 42 } } });
const r = messages.find((m) => m.type === "done");
fs.writeFileSync("prototype/align_debug.json", JSON.stringify({ points: pts, curve: r.curve, tm_js: r.target_machine, params: r.params }));
console.log("exported");
